# Generated by Django 5.0.2 on 2024-03-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
