# Generated by Django 5.0.2 on 2024-03-03 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='brand',
        ),
    ]
