# Generated by Django 5.0.2 on 2024-03-03 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_rename_title_post_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='title',
        ),
    ]
