# Generated by Django 5.0.2 on 2024-03-03 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_rename_name_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='brand',
            new_name='category',
        ),
    ]
